### ISSUE TITLE
Docker und Git Probleme

### ISSUE THREAD

**Issue by Monab3** [smurzz/artconnect#12]
Problem Beschreibung:

- Docker lädt immer die Änderungen eines Branches.

- Das Frontend-Team und das Backend-Team arbeiten simultan an verschiedenen Branches, die vom Master abzweigen.

- Docker kann nur einen Branch zur Zeit laden. Wenn das Frontend-Team seinen Branch über Docker startet, fehlen ihm die Inhalte, die das Backend-Team erarbeitet hat, sofern das Backend-Team seine Änderungen noch nicht in den Master gepusht hat.

Aufgabe: 

- Sofya erklärt Mona wie die arbeit mit Docker funktioniert anschließend: 

- Entwicklung gemeinsamer Strategielösungen, damit das Frontend- und Backend-Team effektiv zusammenarbeiten können.

**Comment by Monab3** [comment]
Lösungsstrategie und Anleitung zum Arbeiten mit den Branches: 

1. FE-Team und BE-Team sprechen sich intern ab, wie sie ihre Branches verwalten wollen
Möglichkeiten: 
- Zusammen an einem Branch arbeiten:
Problem: Wenn einer der Partner Code committed, muss dem anderen Bescheid gegeben werden, damit er entsprechend rebasen kann.
- Zwei verschiedene Branches: 
Löst das Problem von oben. Falls der Code des jeweils anderen benötigt wird, kann gemerged, rebased oder cherrypicked werden.

2. Wenn eine neue Funktion (egal ob im Backend oder im Frontend) entwickelt wurde und funktioniert, sollte das Team darüber informiert werden dass die Implementierung des neuen Features abgeschlossen ist.  Am besten das neue Feature auch noch einmal dem Team präsentieren. Anschließend kann der Code in den Master gepusht werden

3. Alle bestehenden Branches, die vom Master abzweigen, sollten rebased werden, um den neuen Codestand zu erhalten.

**Comment by smurzz** [comment]
Als Lösungsoption für die Problembehandlung schlage ich Folgendes vor:

Ich habe einen zusätzlichen Review-Branch mit dem Namen "**_div_**" erstellt. In diesem Branch werden wir unsere endgültigen Lösungen für Funktionen, Fehlerbehebungen oder Ergänzungen präsentieren. Dies sollten wir ausschließlich über Pull Requests durchführen. Wenn etwas nicht stimmt oder weitere Nacharbeiten erforderlich sind, können wir dies in den Kommentaren unten diskutieren. Wenn alle Änderungen akzeptiert werden, können wir den Pull Request mit dem Merge abschließen. Sobald Backend und Frontend für eine bestimmte Funktion fertig sind, können wir den Merge mit dem "main"-Branch durchführen.

Außerdem habe ich einige Updates in der [_docker.yml_-Workflow-Action](https://github.com/smurzz/artconnect/blob/main/.github/workflows/docker.yml) in **ALLEN** Branchs vorgenommen. Die Action wird nun **NUR** durch Pushes in den "**_dev_**" und "**_main_**"-Branches ausgelöst. Dadurch werden nur abgeschlossene Zustände von Backend und Frontend in den Docker-Images enthalten sein. 
**[WICHTIG]** Bitte führt vor dem Erstellen eines Pull Requests im "**_dev_**"-Branch ein "`git pull`" auf eurem lokalen System aus.

Wir können die vorgenommenen Änderungen eine Weile lang testen. Wenn euch etwas einfällt, meldet es bitte hier in den Kommentaren oder schreibt es in Discord.

**[WICHTIG]** Bitte zieht alle Änderungen auf eurem lokalen System(`git pull`), wenn ihr in den folgenden Branches arbeitet:

- aaron
- auth_tests_komola
- auth_tests_ozi
- dataandrouting
- test_frontend
