### ISSUE TITLE
User Controller/Service in Backend

### ISSUE THREAD

**Issue by smurzz** [smurzz/artconnect#17]
**User Model erweitern:**

1. Profilbild;
2. Biografie/Beschreibung;
3. Gallerie;
4. _Ausstellungen/Auszeichnungen;_
5. Kontaktdaten (Telefonnummer, Adresse oder Website)
6. Social-Media-Profile ( Links zu ihren Social-Media-Profilen (z.B. Instagram, Facebook, Twitter))

Bitte hinterlasst eure Vorschläge für User-Attribute in den Kommentaren.

**Comment by Monab3** [comment]
5.geburtstdatum

**Comment by smurzz** [comment]
1. **Der Endpunkt wurde als unnötig entfernt.**
_GET_ http://localhost:8080/

**Comment by smurzz** [comment]
2. **Die Darstellung der Fehlermeldung aus der Validierung wurde in [commit](https://github.com/smurzz/artconnect/commit/d1f951428e9156d06ce7bed1bd74) geändert:**

Beispiel:

{
    "timestamp": "2023-06-15T06:51:23.002+00:00",
    "path": "/auth/register",
    "status": 400,
    "error": "Bad Request",
    "message": "email: muss eine korrekt formatierte E-Mail-Adresse sein, password: Größe muss zwischen 3 und 20 sein",
    "requestId": "654bfca5-5",
    ... }

**Comment by smurzz** [comment]
3. **User-Änderungen, hinzugefügte Attribute:**

- [ ] `profilePhoto`: [_Datentyp_: [Image](https://github.com/smurzz/artconnect/blob/05defbaaba76ad1be0dbe2aac51ec8cfcf576cb2/ac-backend/src/main/java/com/artconnect/backend/model/Image.java)]
- [ ] `dateOfBirthday`: [_Datentyp_: LocalDate]
- [ ] `isDateOfBirthVisible`: [_Datentyp_: [Status](https://github.com/smurzz/artconnect/blob/05defbaaba76ad1be0dbe2aac51ec8cfcf576cb2/ac-backend/src/main/java/com/artconnect/backend/model/user/Status.java)]
- [ ] ~~isEnabled: [_Datentyp_: Boolean]~~ -> `isAccountEnabled`: [_Datentyp_: [Status](https://github.com/smurzz/artconnect/blob/05defbaaba76ad1be0dbe2aac51ec8cfcf576cb2/ac-backend/src/main/java/com/artconnect/backend/model/user/Status.java)]
- [ ] `biography`: [_Datentyp_: String]
- [ ] `exhibitions`: [_Datentyp_: List<[Exhibition](https://github.com/smurzz/artconnect/blob/05defbaaba76ad1be0dbe2aac51ec8cfcf576cb2/ac-backend/src/main/java/com/artconnect/backend/model/user/Exhibition.java)>]
- [ ] `contacts`: [_Datentyp_: [Contacts](https://github.com/smurzz/artconnect/blob/05defbaaba76ad1be0dbe2aac51ec8cfcf576cb2/ac-backend/src/main/java/com/artconnect/backend/model/user/Contacts.java)]
- [ ] `socialMedias`: _Datentyp_: List<[SocialMedia](https://github.com/smurzz/artconnect/blob/user-backend/ac-backend/src/main/java/com/artconnect/backend/model/user/SocialMedia.java)>

**Comment by smurzz** [comment]
## Find All Users:
#### Öffentlich (für Gäste und Benutzer)

1. _GET_ http://localhost:8080/users

_Response Status:_ **200**

_Beispiel:_

 ```
[
    {
        "id": "648858390316f339a4d2ebdc",
        "firstname": "Max",
        "lastname": "Mustermann",
        "dateOfBirthday": "1995-05-05",
        "createdAt": "2023-06-13T11:51:21.482+00:00",
        "profilePhoto": null,
        "biography": "BlaBlaBla",
        "exhibitions": [
            {
                "title": "Exhibition1",
                "location": "Nowhere",
                "year": 2000,
                "description": "BlaBlaBla"
            },
            {
                "title": "Exhibition1",
                "location": "Somewhere",
                "year": 2020,
                "description": "BlaBlaBla"
            }
        ],
        "contacts": {
            "telefonNumber": 123456789,
            "address": {
                "street": "Street Str.",
                "postalCode": "12345",
                "city": "City",
                "country": "Country"
            },
            "website": "http://site.com"
        },
        "socialMedias": [
            {
                "title": "Etsy",
                "link": "http://etsy.com/myAccount"
            },
            {
                "title": "Instagram",
                "link": "http://instagram.com/myAccount"
            }
        ]
    },
    {
        "id": "648858ab0316f339a4d2ebdd",
        "firstname": "admin",
        "lastname": "admin",
        "dateOfBirthday": null,
        "createdAt": "2023-06-13T11:53:15.169+00:00",
        "profilePhoto": null,
        "biography": null,
        "exhibitions": null,
        "contacts": null,
        "socialMedias": null
    }
]
```

**Comment by smurzz** [comment]
## Find User by Id:
#### Öffentlich (für Gäste und Benutzer)

2. GET http://localhost:8080/users/{id}

_Request path variable:_ **id**
_Request Status:_ **200**
_Request Error Status:_ **404**

_Beispiel:_ http://localhost:8080/users/648858390316f339a4d2ebdc 

_Response:_

```
{
    "id": "648858390316f339a4d2ebdc",
    "firstname": "Max",
    "lastname": "Mustermann",
    "dateOfBirthday": "1995-05-05",
    "createdAt": "2023-06-13T11:51:21.482+00:00",
    "profilePhoto": null,
    "biography": "BlaBlaBla",
    "exhibitions": [
        {
            "title": "Exhibition1",
            "location": "Nowhere",
            "year": 2000,
            "description": "BlaBlaBla"
        },
        {
            "title": "Exhibition1",
            "location": "Somewhere",
            "year": 2020,
            "description": "BlaBlaBla"
        }
    ],
    "contacts": {
        "telefonNumber": 123456789,
        "address": {
            "street": "Street Str.",
            "postalCode": "12345",
            "city": "City",
            "country": "Country"
        },
        "website": "http://site.com"
    },
    "socialMedias": [
        {
            "title": "Etsy",
            "link": "http://etsy.com/myAccount"
        },
        {
            "title": "Instagram",
            "link": "http://instagram.com/myAccount"
        }
    ]
}
```

**Comment by smurzz** [comment]
## Find User by Email:
#### Öffentlich (für Gäste und Benutzer)

3. GET http://localhost:8080/users

_Request Parameter:_ **email**
_Request Status:_ **200**
_Request Error Status:_ **404**

_Beispiel_: http://localhost:8080/users?email=max.mustermann@gmail.com

_Response:_

```
{
    "id": "648858390316f339a4d2ebdc",
    "firstname": "Max",
    "lastname": "Mustermann",
    "dateOfBirthday": "1995-05-05",
    "createdAt": "2023-06-13T11:51:21.482+00:00",
    "profilePhoto": null,
    "biography": "BlaBlaBla",
    "exhibitions": [
        {
            "title": "Exhibition1",
            "location": "Nowhere",
            "year": 2000,
            "description": "BlaBlaBla"
        },
        {
            "title": "Exhibition1",
            "location": "Somewhere",
            "year": 2020,
            "description": "BlaBlaBla"
        }
    ],
    "contacts": {
        "telefonNumber": 123456789,
        "address": {
            "street": "Street Str.",
            "postalCode": "12345",
            "city": "City",
            "country": "Country"
        },
        "website": "http://site.com"
    },
    "socialMedias": [
        {
            "title": "Etsy",
            "link": "http://etsy.com/myAccount"
        },
        {
            "title": "Instagram",
            "link": "http://instagram.com/myAccount"
        }
    ]
}

```

**Comment by smurzz** [comment]
## Update User:
#### Privat (nur für Benutzer)

4. PUT http://localhost:8080/users/

_Request Headers:_  Authentication: Bearer [access-token]
_Request body:_ **{ firstname, lastname, dateOfBirthday, isDateOfBirthVisible, biography, exhibitions, contacts, socialMedias }** **
** <sub>**password** ist eine sensitive Daten, die man mit einer getrennten Anfrage änderen sollte. Können wir später implementieren.</sub>
** <sub>**alle Parameter** sind optional, die Anfrage muss jedoch mindestens einen Parameter enthalten</sub>

_Response Status:_ **200**
_Response Error Status:_ **401, 404**

_Beispiel_: http://localhost:8080/users/648858390316f339a4d2ebdc

_Request Body_:
```
{
    "dateOfBirthday": "1995-05-05",
    "isDateOfBirthVisible": "PUBLIC",
    "biography": "BlaBlaBla",
    "exhibitions": [
        {
            "title": "Exhibition1",
            "location": "Nowhere",
            "year": 2000,
            "description": "BlaBlaBla"
        },
        {
            "title": "Exhibition1",
            "location": "Somewhere",
            "year": 2020,
            "description": "BlaBlaBla"
        }
    ],
    "contacts": {
        "telefonNumber": 123456789,
        "address": {
            "street": "Street Str.",
            "postalCode": 12345,
            "city": "City",
            "country": "Country"
        },
        "website": "http://site.com"
    },
    "socialMedias": [
        {
            "title": "Etsy",
            "link": "http://etsy.com/myAccount"
        },
        {
            "title": "Instagram",
            "link": "http://instagram.com/myAccount"
        }
    ]
}
```

_Response Body:_

```
{
    "id": "648858390316f339a4d2ebdc",
    "firstname": "Max",
    "lastname": "Mustermann",
    "dateOfBirthday": "1995-05-05",
    "createdAt": "2023-06-13T11:51:21.482+00:00",
    "profilePhoto": null,
    "biography": "BlaBlaBla",
    "exhibitions": [
        {
            "title": "Exhibition1",
            "location": "Nowhere",
            "year": 2000,
            "description": "BlaBlaBla"
        },
        {
            "title": "Exhibition1",
            "location": "Somewhere",
            "year": 2020,
            "description": "BlaBlaBla"
        }
    ],
    "contacts": {
        "telefonNumber": 123456789,
        "address": {
            "street": "Street Str.",
            "postalCode": "12345",
            "city": "City",
            "country": "Country"
        },
        "website": "http://site.com"
    },
    "socialMedias": [
        {
            "title": "Etsy",
            "link": "http://etsy.com/myAccount"
        },
        {
            "title": "Instagram",
            "link": "http://instagram.com/myAccount"
        }
    ]
}
```

**Comment by smurzz** [comment]
## Delete User:
#### Privat (nur für Benutzer)

5. DELETE http://localhost:8080/users/{id}

_Request Headers:_ Authentication: Bearer [access-token]

_Request path variable:_ **id**
_Beispiel:_ http://localhost:8080/users/648858390316f339a4d2ebdc

_Response Status:_ **204**
_Response Error Status:_ **401, 404**

**Comment by smurzz** [comment]
## Add Profile photo:
#### Privat (nut für Benutzer)

6. _POST_ http://localhost:8080/users/profile-photo

_Request Headers:_ Authentication: Bearer [access-token]
_Request Headers:_ Content-type: multipart/form-data
_Request Parameter:_ file

_Response Body:_ **_Base64-Bild_**
_Response Status_: _**201**_
_Response Error Status_: **_401, 404, 500_**

**Validierung:**
_Akzeptable Bildformate:_ _**.jpg, .jpeg, .png**_
_Maximale Bildgröße:_ _**5Mb**_

**[FRONTEND]** @Monab3 

_Request-Beispiel im Frontend:_

`<input type="file" ...>`

...

```
const [selectedFile, setSelectedFile] = useState(null);

const formData = new FormData();
formData.append('file', selectedFile);

const requestOptions = {
                headers: {
                    "Content-type": "multipart/form-data"
                }
     }
     
 axios.post('/users/profile-photo', formData, requestOptions)
 .then(response => {
       const photoData = btoa(
               new Uint8Array(response.data).reduce((data, byte) => data + String.fromCharCode(byte), '')
       ); 
       const contentType = response.headers['content-type'];
       const imageUrl = `data:${contentType};base64,${photoData}`;
 })
```
 ...
 
` <img src={imageUrl} ... />`

**Comment by smurzz** [comment]
## Fild Users Profile photo:
#### Öffentlich (für Gäste und Benutzer)

7. POST http://localhost:8080/users/{id}/profile-photo

_Request Headers:_ Authentication: Bearer [access-token]
_Request path variable:_ **id**

_Response Body:_ **Base64-Bild**
_Response Status:_ **200**
_Response Error Status:_ **404**

**Comment by smurzz** [comment]
## Fild Users by Firstname and/or by Lastname :
#### Öffentlich (für Gäste und Benutzer)

7. GET http://localhost:8080/users/search

_Request Parameter:_ _**firstname**_, * _**lastname**_ *
<sub>*optionaler Parameter</sub>

_Response Status:_ _**200**_
_Request Body:_ **_Array<[UserResponse](https://github.com/smurzz/artconnect/blob/user-backend/ac-backend/src/main/java/com/artconnect/backend/controller/response/UserResponse.java)>_**

_Beispiel:_ http://localhost:8080/users/search?firstname=mark
_Beispiel Response Body:_
```
[
    {
        "id": "6497b5cf9c0a554bb7ec6a39",
        "firstname": "Mark",
        "lastname": "Black",
        "dateOfBirthday": null,
        "createdAt": "2023-06-25T03:34:39.641+00:00",
        "profilePhoto": null,
        "biography": null,
        "exhibitions": null,
        "contacts": null,
        "socialMedias": null
    },
    {
        "id": "6497b5eb9c0a554bb7ec6a3b",
        "firstname": "Mark",
        "lastname": "Veber",
        "dateOfBirthday": null,
        "createdAt": "2023-06-25T03:35:06.848+00:00",
        "profilePhoto": null,
        "biography": null,
        "exhibitions": null,
        "contacts": null,
        "socialMedias": null
    }
]
```

_Beispiel:_ http://localhost:8080/users/search?firstname=mark&lastname=Black
_Beispiel Response Body:_
```
[
    {
        "id": "6497b5cf9c0a554bb7ec6a39",
        "firstname": "Mark",
        "lastname": "Black",
        "dateOfBirthday": null,
        "createdAt": "2023-06-25T03:34:39.641+00:00",
        "profilePhoto": null,
        "biography": null,
        "exhibitions": null,
        "contacts": null,
        "socialMedias": null
    },
]
```

_Beispiel:_ http://localhost:8080/users/search?lastname=Veber
_Beispiel Response Body:_
``` 
[
    {
         "id": "6497b5eb9c0a554bb7ec6a3b",
        "firstname": "Mark",
        "lastname": "Veber",
        "dateOfBirthday": null,
        "createdAt": "2023-06-25T03:35:06.848+00:00",
        "profilePhoto": null,
        "biography": null,
        "exhibitions": null,
        "contacts": null,
        "socialMedias": null
    },
] 
```
