### ISSUE TITLE
Vorbereitung Playtest

### ISSUE THREAD

**Issue by Monab3** [smurzz/artconnect#32]
- Funktionen Testen
- Features glattziehen
- Letzte Änderungen einfüge
- Branches im Dev-Branch von Git zusammen führe
- Walkthrough durch die App erstellen
- Feedbackformular erstellen

**Comment by Atze-Schron** [comment]
ggf. bitte noch das feedback hier einbinden bzw.im  wiki eintragen

**Comment by Monab3** [comment]
Walkthrough und Feedbackbogen befinden sich in der read.me des  Projektes
