### ISSUE TITLE
docker und aws  einarbeiten für deplyoment

### ISSUE THREAD

**Issue by Atze-Schron** [smurzz/artconnect#46]

**Comment by ZacUpshure** [comment]
1. Docker Container Vorbereiten: Build und tag von Docker image für jeden Kontainer
2. "Container Registry": Docker Images auf Container Registry hochladen Amazon Elastic Container Registry (ECR) oder DockerHub
3. Amazon ECS oder Amazon EKS: 

"Amazon Elastic Container Service (ECS) is a fully managed container orchestration service."
"Amazon Elastic Kubernetes Service (EKS) provides managed Kubernetes clusters."

Amazon ECS: Erstellen Sie einen ECS-Cluster und Aufgabendefinitionen für jeden Container. Aufgabendefinitionen geben das Container-Image, Ressourcenanforderungen, Netzwerk und andere Konfigurationen an. Erstellen Sie dann einen ECS-Dienst zur Verwaltung der Container, einschließlich automatischer Skalierung, Lastausgleich und Überwachung.

Amazon EKS: Richten Sie einen EKS-Cluster ein und definieren Sie Kubernetes-Manifeste (Bereitstellung, Service usw.) für jeden Container. Die Manifeste beschreiben den gewünschten Zustand Ihrer Container und Kubernetes sorgt dafür, dass der gewünschte Zustand im Cluster erreicht wird.

1. Networking: networking configuration für container, VPC, subnets, load balancers.
2. Deployment: AWS CLI, AWS Management Console.

**Comment by smurzz** [comment]
**Für das Deployment die Anwendung auf AWS EC2 mit Docker wurden die folgenden Schritte durchgeführt:**

1. Herstellung einer EC2-Instanz auf AWS (Betriebssystem - Ubuntu).

2. Installation von Docker: Nachdem die EC2-Instanz erstellt wurde, wurde Docker auf der Instanz installiert.

3.  Installation von Git auf die EC2-Instanz.

4. Klonierung des Projekt-Repositories auf die EC2-Instanz.

5. Starten des Containers:  Docker-Container wurde aus dem Repository-Projekt gestartet. Der Container basiert auf den Images und enthält die Anwendungsteile.

6. Konfiguration der Security Groups: Security Groups wurden für die EC2-Instanz konfiguriert, um den Zugriff auf die gewünschten Ports zu ermöglichen. Dadurch kann der Container über das Netzwerk erreichbar sein.

-------------------------------------------------------------------------------------------------------------------------
_**In der Bearbeitung:**_ 
- Übertragung der DB des Docker Profils in Atlas Cluster
- Erstellung CI/CD Pipeline für die automatische Containeraktualidierung in EC2 Instance
