### ISSUE TITLE
Gallery_Atwork Tests Komola

### ISSUE THREAD

**Issue by smurzz** [smurzz/artconnect#62]

**Comment by KomolaBZR** [comment]
Coverage on New Code - 69.0%

The tests were written for the following Java classes and packages: 

-	validation: MaxYear.java, NotBlankIfSpecified.java, ValidArtDirection.java, ValidGalleryCategory.java. 
-	service: ValidGalleryCategory.java, CommentService.java, GalleryService.java, ImageService.java, RatingService.java, UserService.java
-	model: 
                      - artwork: ArtDirection.java, ArtWork.java, Comment.java, Dimension.java
                      - gallery: Gallery.java, GalleryCategory.java
                      - user: Contacts.java, Exhibition.java, User.java
-	controller: ArtWorkController.java, CommentController.java, GalleryController.java, ImageController.java, RatingController.java
-	controller: 
                       - request: ArtWorkRequest.java, ArtWorkUpdateRequest.java, CommentRequest.java, CommentUpdateRequest.java, GalleryRequest.java
                       - response: ArtWorkResponse.java, GalleryResponse.java, ValidationHandler.java
